productos/config/routes.rb
Rails.application.routes.draw do
  resources :productos

end

productos/app/models/producto.rb
class Producto < ActiveRecord::Base
end

productos/app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
    #@productos = Producto.find(10)
    #@productos = Producto.take(10)
    #@productos = Producto.first
    #@productos = Producto.last
    #productos = Producto.find_by_color("blanco")
    @productos = Producto.where(talla: ["s", "l"])
    #@productos = Producto.where.not(talla: ["s", "l"])
    #@productos = Producto.where.not(talla: ["s", "l"])
    #@productos = Producto.order(precio: :desc)
    #@productos = Producto.select(:costo, :precio)
    #@productos = Producto.limit(5).offset(10)
    #@productos = Producto.limit(5).offset(10)
    #@productos = Producto.group(:talla)
    #@productos = Producto.group(:tipo).having("sum(precio) > ?", 2800000)
    #@productos = Producto.all.readonly
    #@productos = Producto.includes(:categoria).limit(10)
    #@productos = Producto.where("cantidad > ? AND tipo = ?", 100, "hombre")
    #@productos = Producto.where("descripcion like  ? ",  "%niño%")
    #pluck, sum, minimum, maximum, average


  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:referencia, :color, :talla, :categoria, :tipo, :marca, :descripcion, :tela, :cantidad, :costo, :precio)
    end
end

productos/app/helpers/productos_helper.rb
module ProductosHelper
end

productos/app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :referencia %><br>
    <%= f.text_field :referencia %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :talla %><br>
    <%= f.text_field :talla %>
  </div>
  <div class="field">
    <%= f.label :categoria %><br>
    <%= f.text_field :categoria %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :marca %><br>
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :tela %><br>
    <%= f.text_field :tela %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :costo %><br>
    <%= f.text_field :costo %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.text_field :precio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

productos/app/views/productos/edit.html.erb
<h1>Editing Producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

productos/app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Productos</h1>

<table>
  <thead>
    <tr>
      <th>Referencia</th>
      <th>Color</th>
      <th>Talla</th>
      <th>Categoria</th>
      <th>Tipo</th>
      <th>Marca</th>
      <th>Descripcion</th>
      <th>Tela</th>
      <th>Cantidad</th>
      <th>Costo</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.referencia %></td>
        <td><%= producto.color %></td>
        <td><%= producto.talla %></td>
        <td><%= producto.categoria %></td>
        <td><%= producto.tipo %></td>
        <td><%= producto.marca %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.tela %></td>
        <td><%= producto.cantidad %></td>
        <td><%= producto.costo %></td>
        <td><%= producto.precio %></td>
        <td><%= link_to 'Show', producto %></td>
        <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
        <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producto', new_producto_path %>

productos/app/views/productos/new.html.erb
<h1>New Producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

productos/app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Referencia:</strong>
  <%= @producto.referencia %>
</p>

<p>
  <strong>Color:</strong>
  <%= @producto.color %>
</p>

<p>
  <strong>Talla:</strong>
  <%= @producto.talla %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @producto.categoria %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @producto.tipo %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @producto.marca %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @producto.descripcion %>
</p>

<p>
  <strong>Tela:</strong>
  <%= @producto.tela %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @producto.cantidad %>
</p>

<p>
  <strong>Costo:</strong>
  <%= @producto.costo %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @producto.precio %>
</p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>