Clinica/config/routes.rb
Rails.application.routes.draw do
  resources :women
  resources :childds

end

Clinica/app/models/child.rb
class Child < ActiveRecord::Base
end

Clinica/app/models/childd.rb
class Childd < ActiveRecord::Base
end

Clinica/app/models/woman.rb
class Woman < ActiveRecord::Base
end

Clinica/app/controllers/childds_controller.rb
class ChilddsController < ApplicationController
  before_action :set_childd, only: [:show, :edit, :update, :destroy]

  # GET /childds
  # GET /childds.json
  def index
    @childds = Childd.all
  end

  # GET /childds/1
  # GET /childds/1.json
  def show
  end

  # GET /childds/new
  def new
    @childd = Childd.new
  end

  # GET /childds/1/edit
  def edit
  end

  # POST /childds
  # POST /childds.json
  def create
    @childd = Childd.new(childd_params)

    respond_to do |format|
      if @childd.save
        format.html { redirect_to @childd, notice: 'Childd was successfully created.' }
        format.json { render :show, status: :created, location: @childd }
      else
        format.html { render :new }
        format.json { render json: @childd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /childds/1
  # PATCH/PUT /childds/1.json
  def update
    respond_to do |format|
      if @childd.update(childd_params)
        format.html { redirect_to @childd, notice: 'Childd was successfully updated.' }
        format.json { render :show, status: :ok, location: @childd }
      else
        format.html { render :edit }
        format.json { render json: @childd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /childds/1
  # DELETE /childds/1.json
  def destroy
    @childd.destroy
    respond_to do |format|
      format.html { redirect_to childds_url, notice: 'Childd was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_childd
      @childd = Childd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def childd_params
      params.require(:childd).permit(:name, :surname, :lastname, :secondlastname, :ti, :age, :sex, :name_mother, :name_father, :vacuna1, :vacuna2, :vacuna3, :vacuna4, :cancer, :hipertencion, :diabetes, :otra, :enfermedades, :desnutricion, :grupo_sanguineo)
    end
end

Clinica/app/controllers/women_controller.rb
class WomenController < ApplicationController
  before_action :set_woman, only: [:show, :edit, :update, :destroy]

  # GET /women
  # GET /women.json
  def index
    @women = Woman.all
  end

  # GET /women/1
  # GET /women/1.json
  def show
  end

  # GET /women/new
  def new
    @woman = Woman.new
  end

  # GET /women/1/edit
  def edit
  end

  # POST /women
  # POST /women.json
  def create
    @woman = Woman.new(woman_params)

    respond_to do |format|
      if @woman.save
        format.html { redirect_to @woman, notice: 'Woman was successfully created.' }
        format.json { render :show, status: :created, location: @woman }
      else
        format.html { render :new }
        format.json { render json: @woman.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /women/1
  # PATCH/PUT /women/1.json
  def update
    respond_to do |format|
      if @woman.update(woman_params)
        format.html { redirect_to @woman, notice: 'Woman was successfully updated.' }
        format.json { render :show, status: :ok, location: @woman }
      else
        format.html { render :edit }
        format.json { render json: @woman.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /women/1
  # DELETE /women/1.json
  def destroy
    @woman.destroy
    respond_to do |format|
      format.html { redirect_to women_url, notice: 'Woman was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_woman
      @woman = Woman.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def woman_params
      params.require(:woman).permit(:name, :surname, :lastname, :secondlastname, :documento_id, :fecha_de_nacimiento, :estado_civil, :numero_de_hijos, :numero_de_abortos, :problemas_de_embarazo, :cancer_de_ovarios, :cancer_de_mamas, :algun_otro_cancer, :hipertencion, :diabetes, :alzheimer, :grupo_sanguineo, :otra, :enfermedades, :grupo_sanguineo, :enfermedades_o_tratamientos_actitudes)
    end
end

Clinica/app/helpers/childds_helper.rb
module ChilddsHelper
end

Clinica/app/helpers/women_helper.rb
module WomenHelper
end

Clinica/app/views/childds/_form.html.erb
<%= form_for(@childd) do |f| %>
  <% if @childd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@childd.errors.count, "error") %> prohibited this childd from being saved:</h2>

      <ul>
      <% @childd.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :secondlastname %><br>
    <%= f.text_field :secondlastname %>
  </div>
  <div class="field">
    <%= f.label :ti %><br>
    <%= f.number_field :ti %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :sex %><br>
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :name_mother %><br>
    <%= f.text_field :name_mother %>
  </div>
  <div class="field">
    <%= f.label :name_father %><br>
    <%= f.text_field :name_father %>
  </div>
  <div class="field">
    <%= f.label :vacuna1 %><br>
    <%= f.text_field :vacuna1 %>
  </div>
  <div class="field">
    <%= f.label :vacuna2 %><br>
    <%= f.text_field :vacuna2 %>
  </div>
  <div class="field">
    <%= f.label :vacuna3 %><br>
    <%= f.text_field :vacuna3 %>
  </div>
  <div class="field">
    <%= f.label :vacuna4 %><br>
    <%= f.text_field :vacuna4 %>
  </div>
  <div class="field">
    <%= f.label :cancer %><br>
    <%= f.text_field :cancer %>
  </div>
  <div class="field">
    <%= f.label :hipertencion %><br>
    <%= f.text_field :hipertencion %>
  </div>
  <div class="field">
    <%= f.label :diabetes %><br>
    <%= f.text_field :diabetes %>
  </div>
  <div class="field">
    <%= f.label :otra %><br>
    <%= f.text_field :otra %>
  </div>
  <div class="field">
    <%= f.label :enfermedades %><br>
    <%= f.text_field :enfermedades %>
  </div>
  <div class="field">
    <%= f.label :desnutricion %><br>
    <%= f.text_field :desnutricion %>
  </div>
  <div class="field">
    <%= f.label :grupo_sanguineo %><br>
    <%= f.text_field :grupo_sanguineo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Clinica/app/views/childds/edit.html.erb
<h1>Editing Childd</h1>

<%= render 'form' %>

<%= link_to 'Show', @childd %> |
<%= link_to 'Back', childds_path %>

Clinica/app/views/childds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Childds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Lastname</th>
      <th>Secondlastname</th>
      <th>Ti</th>
      <th>Age</th>
      <th>Sex</th>
      <th>Name mother</th>
      <th>Name father</th>
      <th>Vacuna1</th>
      <th>Vacuna2</th>
      <th>Vacuna3</th>
      <th>Vacuna4</th>
      <th>Cancer</th>
      <th>Hipertencion</th>
      <th>Diabetes</th>
      <th>Otra</th>
      <th>Enfermedades</th>
      <th>Desnutricion</th>
      <th>Grupo sanguineo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @childds.each do |childd| %>
      <tr>
        <td><%= childd.name %></td>
        <td><%= childd.surname %></td>
        <td><%= childd.lastname %></td>
        <td><%= childd.secondlastname %></td>
        <td><%= childd.ti %></td>
        <td><%= childd.age %></td>
        <td><%= childd.sex %></td>
        <td><%= childd.name_mother %></td>
        <td><%= childd.name_father %></td>
        <td><%= childd.vacuna1 %></td>
        <td><%= childd.vacuna2 %></td>
        <td><%= childd.vacuna3 %></td>
        <td><%= childd.vacuna4 %></td>
        <td><%= childd.cancer %></td>
        <td><%= childd.hipertencion %></td>
        <td><%= childd.diabetes %></td>
        <td><%= childd.otra %></td>
        <td><%= childd.enfermedades %></td>
        <td><%= childd.desnutricion %></td>
        <td><%= childd.grupo_sanguineo %></td>
        <td><%= link_to 'Show', childd %></td>
        <td><%= link_to 'Edit', edit_childd_path(childd) %></td>
        <td><%= link_to 'Destroy', childd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Childd', new_childd_path %>

Clinica/app/views/childds/new.html.erb
<h1>New Childd</h1>

<%= render 'form' %>

<%= link_to 'Back', childds_path %>

Clinica/app/views/childds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @childd.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @childd.surname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @childd.lastname %>
</p>

<p>
  <strong>Secondlastname:</strong>
  <%= @childd.secondlastname %>
</p>

<p>
  <strong>Ti:</strong>
  <%= @childd.ti %>
</p>

<p>
  <strong>Age:</strong>
  <%= @childd.age %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @childd.sex %>
</p>

<p>
  <strong>Name mother:</strong>
  <%= @childd.name_mother %>
</p>

<p>
  <strong>Name father:</strong>
  <%= @childd.name_father %>
</p>

<p>
  <strong>Vacuna1:</strong>
  <%= @childd.vacuna1 %>
</p>

<p>
  <strong>Vacuna2:</strong>
  <%= @childd.vacuna2 %>
</p>

<p>
  <strong>Vacuna3:</strong>
  <%= @childd.vacuna3 %>
</p>

<p>
  <strong>Vacuna4:</strong>
  <%= @childd.vacuna4 %>
</p>

<p>
  <strong>Cancer:</strong>
  <%= @childd.cancer %>
</p>

<p>
  <strong>Hipertencion:</strong>
  <%= @childd.hipertencion %>
</p>

<p>
  <strong>Diabetes:</strong>
  <%= @childd.diabetes %>
</p>

<p>
  <strong>Otra:</strong>
  <%= @childd.otra %>
</p>

<p>
  <strong>Enfermedades:</strong>
  <%= @childd.enfermedades %>
</p>

<p>
  <strong>Desnutricion:</strong>
  <%= @childd.desnutricion %>
</p>

<p>
  <strong>Grupo sanguineo:</strong>
  <%= @childd.grupo_sanguineo %>
</p>

<%= link_to 'Edit', edit_childd_path(@childd) %> |
<%= link_to 'Back', childds_path %>